### ISSUE TITLE
TPM-slb9670 with rpi4b tpm_tis_spi_probe: missing reset GPIO tpm_tis_spi_probe: no device found Couldn't set TPM 0 (rc = 1) error

### ISSUE THREAD

**Issue by Rahul-Ravichandran** [joholl/rpi4-uboot-tpm#7]
Hi I have been working to set up tom slb 9670 https://www.infineon.com/dgdl/Infineon-OPTIGA_SLx_9670_TPM_2.0_Pi_4-ApplicationNotes-v07_19-EN.pdf?fileId=5546d4626c1f3dc3016c3d19f43972eb with rpi4b. I have been  following your work but the Only difference is that I am running Ubuntu server 20 instead of raspbian. when i enter u-boot and enter "tpm2 init" , i get errors like:

tpm_tis_spi_probe: missing reset GPIO
 tpm_tis_spi_probe: no device found
 Couldn't set TPM 0 (rc = 1)

I have looked through all the issues disscussed but i couldnt get it to work.

Could you help me please

**Comment by joholl** [comment]
`tpm_tis_spi_probe: missing reset GPIO` can be ignored for now. The problem is probably due to communication problems which might be rooted in bad wiring, a bad device tree configuration or a bad config.txt. I'd suggest double checking the device tree, cranking up logging for U-Boot and write the logs to a file on your laptop. If that doesn't give any clue, you might need to have a look at the SPI communication using a scope.

**Comment by Rahul-Ravichandran** [comment]
I figured out the issue why it was not connecting. Apart from the dtoverlay in the config file, it is also necessary to add "tpm_tis_spi" in "/etc/modules". Then it finds the tpm module and connects to it

**Comment by Rahul-Ravichandran** [comment]
i am also making a custom device tree for tpm module to connect to spi6 , but i am having trouble adding the IRQ pin of it. Do you know how?
Btw this is my dts file. Do have a look at it
[tpm-slb8670-spi6.txt](https://github.com/joholl/rpi4-uboot-tpm/files/7209631/tpm-slb8670-spi6.txt)

**Comment by joholl** [comment]
Thanks for your solution. Unfortunately I don't have any experience with doing it via an interrupt. If you figure it out, however, I'd be glad if you could post how you solved it!

**Comment by parthghughri** [comment]
> I figured out the issue why it was not connecting. Apart from the dtoverlay in the config file, it is also necessary to add "tpm_tis_spi" in "/etc/modules". Then it finds the tpm module and connects to it

Hello Rahul, 
I am also facing the same issue as yours. It will be really helpful if you can explain a bit about the solution. I added that line in /etc/modules but still getting the same error.
Thanks.

**Comment by Rahul-Ravichandran** [comment]
Hi @parthghughri ,

Diu create a overlay file for tpm and add the dtoverlay in usercfg.txt?

This was my overlay file.
```
/*
 * Device tree overlay for mcp251xfd/can0 on spi0.0
 */

/dts-v1/;
/plugin/;

/ {
    compatible = "brcm,bcm2835", "brcm,bcm2836", "brcm,bcm2708", "brcm,bcm2709", "bcrm,bcm2711";

	/* spi0 cs pin config */
    fragment@0 {
        target = <&spi0_cs_pins>;
        frag0: __overlay__ {
            brcm,pins = <8>; /* gpio18 */
            brcm,function = <1>; /* output */
        };
    };

    /* spi0 config */
    fragment@1 {
        target = <&spi0>;
        frag1: __overlay__ {
            /* needed to avoid dtc warning */
            #adress-cells = <1>;
            #size-cells = <0>;

            status = "okay";
            pinctrl-names = "default";
            pinctrl-0 = <&spi0_pins &spi0_cs_pins>;
            cs-gpios = <&gpio 8 1>;
        };
    };

	fragment@2 {
        target = <&spidev0>;
        __overlay__ {
            status = "disabled";
        };
    };

	fragment@3 {
        target = <&spidev1>;
        __overlay__ {
            status = "disabled";
        };
    };

    /* the interrupt pin of the can-controller */
    fragment@4 {
        target = <&gpio>;
        __overlay__ {
            can0_pins: can0_pins {
                brcm,pins = <7>; /* gpio7,*/
                brcm,function = <0>; /* input */
                phandle = <0x01>;
            };
        };
    };


    /* the spi config of the can-controller itself binding everything together */
    fragment@5 {
        target = <&spi0>;
        __overlay__ {
            /* needed to avoid dtc warning */
            #address-cells = <1>;
            #size-cells = <0>;

            can0: slb9670@0 {
                reg = <0>;
                compatible = "infineon,slb9670", "tis,tpm2-spi", "tcg,tpm_tis-spi";
                pinctrl-names = "default";
                pinctrl-0 = <&can0_pins>;
                spi-max-frequency = <10000000>;
                interrupt-parent = <0xffffffff>;
                interrupts = <7 8>; /* IRQ_TYPE_LEVEL_LOW */
				gpio-reset = <&gpio 7 1>;
            };
        };
    };

    __overrides__ {
        cs_pin = <&frag0>,"brcm,pins:0",
                 <&frag1>,"cs-gpios:4";
        spimaxfrequency = <&can0>,"spi-max-frequency:0";
        interrupt_pin = <&can0_pins>,"brcm,pins:0";
    };
};
```
This was the line i added to usercfg.txt---"dtoverlay=tpm-soft-spi,cs_pin=8,interrupt_pin=7"

Hope this works

**Comment by parthghughri** [comment]
Thank you for the reply Rahul.

I tried changing tpm-soft-spi.dts with the one you shared but seems it is not detecting the TPM, even when I directly connect the TPM with rpi4.
So I have tried these things: 

1. I've connected rpi4 GPIO pins with a breadboard, and from breadboard to TPM and sorted GPIO pins 6,8,10 with serial to usb adapter and connected that with my laptop/PC using PuTTY to connect. 
![IMG_20220510_153619](https://user-images.githubusercontent.com/16538468/170989087-853aa66f-78b8-49c1-88aa-d34992d702f4.jpg)
in this case, I am getting u-boot shell but TPM is not getting detected (tried with joholl provided tpm-soft-spi.dts as well as yours provided dts), not even in OS after booting.
but when I connect TPM directly with rpi4, without breadboard in between it is getting detected in OS after booting but I cannot get u-boot shell as I do not have a serial connection.


2. So I tried to utilize other UART interfaces, so that TPM is also directly connected with rpi4 and seral is also connected. UART5 seems the best as it uses pin 32-TXD5 and 33-RXD5, hence no need for a breadboard. [Reference](https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-uarts)
![WhatsApp Image 2022-05-30 at 5 48 10 PM](https://user-images.githubusercontent.com/16538468/170991335-d14136d8-0bfa-4f01-8d7c-6885a049d11d.jpeg)
For that, I added line "dtoverlay=uart5,txd5_pin=32,rxd5_pin=33" config.txt and mentioned console=ttyAMA1 in cmdline.txt.
Now I am getting serial output but it is starting from the booting of the kernel and not showing u-boot shell.
`[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd083]`
`[    0.000000] Linux version 5.15.34-v8 (user@user-VirtualBox) (aarch64-linux-gnu-gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #1 SMP PREEMPT Thu Apr 21 17:20:05 IST 2022`
`[    0.000000] Machine model: Raspberry Pi 4 Model B Rev 1.2`
`[    0.000000] efi: UEFI not found.`
`...`
In this case, TPM is getting detected in Raspbian OS, but no u-boot shell. 
Any other way to run u-boot commands and read their output?


Any workaround or other solution/suggestion is appreciated.
Thank you.
